#%RAML 0.8
---
title: link API
baseUri: http://vapi.ca.com

/link:
   /{Title}:
     get:
      description: Returns links
      responses:
        200:
          body:
            application/json:
              example: |
                {
"title": "{Title}",
"description": "Description",
"url": "http://example.com"
}
