#%RAML 0.8
---
title: link API
baseUri: http://vapi.ca.com/api{github_username}/{version}
version: v1

/link:
   /{Title}:
     get:
       description: Retrieve a specific link
       responses:
         200:
           body:
             application/json:
              example: |
                 {
                 "title": "Short Title",
                 "description": "Description",
                 "url": "URL"
 		 },
 		 "success": true,
 		 "status": 200
		}
