#%RAML 0.8
---
title: link-api
baseUri: http://vapi.ca.com
version: 1

/link:
   /{Title}:
     get:
      description: Returns links
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "title": "{Title}",
                  "description": "{{=[::A*(35)]}}",
                  "savedate" : "{{=[:Birthday:]}}",
                  "url": "http://example.com/{{=[::A*(10)]}}.com"
}
