#%RAML 0.8
---
title: link API
baseUri: http://vapi.ca.com
version: 1

/link:
   /{Title}:
     get:
      description: Returns links
      responses:
        200:
          body:
            application/json:
              example: | 
                       {
                        "title": "{Title}",
                        "description": "Description-Short",
                        "url": "http://example.com"
                        }
